title: Introducción a Data Science en R
description: Materiales del curso de Introducción a Data Science, desarrollado para el Min. de Transporte (Argentina)
show_downloads: false
google_analytics: UA-129781054-2
theme: jekyll-theme-architect